name: itr-candidate-form-terraform-cd-stg

on:
  push:
    branches:
      - staging
    paths:
      - "terraform/**"
  workflow_dispatch:

env:
  TF_VERSION: 1.12.2

jobs:
  terraform_apply_stg:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: main checkout
        uses: actions/checkout@v4

      - name: authenticate to aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          # TODO: RoleのARNを、CAILと同じものを使っているので分離する
          role-to-assume: ${{ vars.AWS_IAM_ROLE_TO_ASSUME_STG }}

      - name: generate github apps access token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TECHNOLOGY_STRATEGY_GITHUB_APP_ID }}
          private-key: ${{ secrets.TECHNOLOGY_STRATEGY_GITHUB_APP_PRIVATE_KEY }}
          owner: "lv-technology-strategy"

      - name: github modules checkout
        uses: actions/checkout@v4
        with:
          repository: "lv-technology-strategy/github-actions-modules"
          ref: v1.0.1
          path: ${{ github.workspace }}/.github/modules
          token: ${{ steps.generate_token.outputs.token }}

      # TODO: moduleからコード持ってくる
      - name: terraform cd
        uses: ./.github/modules/actions/terraform-cd
        with:
          github-apps-access-token: ${{ steps.generate_token.outputs.token }}
          notify-tfapply-results: disabled
          terraform-version: ${{ env.TF_VERSION }}
          terraform-dir-rel-path: terraform/environments/stg
